App/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Domain.Models;
using App.DAL;
using App.Enums;
using App.Infrastructure;
using Microsoft.AspNet.Identity;

namespace App.Controllers
{
    public class CategoryEventArgs : EventArgs
    {
        public readonly Category After;
        public readonly CrudEventEnumStatus Status;

        public CategoryEventArgs(Category after, CrudEventEnumStatus status)
        {
            this.After = after;
            this.Status = status;
        }
    }

    [PermissionAuthorization("read_master_data")]
    public class CategoryController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public static event EventHandler<CategoryEventArgs> AfterCall;

        protected virtual void OnCrudOperation(CategoryEventArgs e)
        {
            if (AfterCall != null)
            {
                AfterCall(this, e);
            }
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            ViewBag.Id = id;
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        [PermissionAuthorization("crud_master_data")]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [PermissionAuthorization("crud_master_data")]
        public ActionResult Create(Category category)
        {
            if (ModelState.IsValid)
            {
                db.Categories.Add(category);

                db.SaveChanges(User.Identity.GetUserName());

                OnCrudOperation(new CategoryEventArgs(category, CrudEventEnumStatus.Create));

                if (!string.IsNullOrWhiteSpace(Request.QueryString["createNext"]))
                {
                    if (Request.QueryString["createNext"] == "true")
                    {
                        TempData["Created"] = true;
                        TempData["Alert"] = "Berhasil menambahkan Category";
                        TempData["AlertClass"] = "success";

                        return RedirectToAction("Create");
                    }
                }

                return RedirectToAction("Details", new { id = category.Id});
            }

            TempData["Alert"] = "Gagal menambahkan Category. Harap periksa kembali data yang anda input.";
            TempData["AlertClass"] = "danger";

            return View(category);
        }

        [PermissionAuthorization("crud_master_data")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            ViewBag.Id = id;

            if (category == null)
            {
                return HttpNotFound();
            }

            return View(category);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [PermissionAuthorization("crud_master_data")]
        public ActionResult Edit(Category category)
        {
            if (ModelState.IsValid)
            {
                db.Entry(category).State = EntityState.Modified;

                db.SaveChanges(User.Identity.GetUserName());

                OnCrudOperation(new CategoryEventArgs(category, CrudEventEnumStatus.Update));

                TempData["Alert"] = "Berhasil menyimpan perubahan Category";
                TempData["AlertClass"] = "success";

                return RedirectToAction("Details", new { id = category.Id});
            }
            ViewBag.Id = category.Id;

            TempData["Alert"] = "Gagal melakukan perubahan Category. Harap periksa kembali data yang anda masukkan.";
            TempData["AlertClass"] = "danger";

            return View(category);
        }

        [PermissionAuthorization("crud_master_data")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Category category = db.Categories.Find(id);
            ViewBag.Id = id;

            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [PermissionAuthorization("crud_master_data")]
        public ActionResult DeleteConfirmed(int id)
        {
            Category category = db.Categories.Find(id);
            ViewBag.Id = id;
            db.Categories.Remove(category);
            db.SaveChanges(User.Identity.GetUserName());
            OnCrudOperation(new CategoryEventArgs(category, CrudEventEnumStatus.Delete));
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

App/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Domain.Models;
using App.DAL;
using App.Enums;
using App.Infrastructure;
using Microsoft.AspNet.Identity;

namespace App.Controllers
{
    public class ProductEventArgs : EventArgs
    {
        public readonly Product After;
        public readonly CrudEventEnumStatus Status;

        public ProductEventArgs(Product after, CrudEventEnumStatus status)
        {
            this.After = after;
            this.Status = status;
        }
    }

    [PermissionAuthorization("read_master_data")]
    public class ProductController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public static event EventHandler<ProductEventArgs> AfterCall;

        protected virtual void OnCrudOperation(ProductEventArgs e)
        {
            if (AfterCall != null)
            {
                AfterCall(this, e);
            }
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            ViewBag.Id = id;
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        [PermissionAuthorization("crud_master_data")]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [PermissionAuthorization("crud_master_data")]
        public ActionResult Create(Product product)
        {
            if (ModelState.IsValid)
            {
                product.Id = Guid.NewGuid();
                db.Products.Add(product);

                db.SaveChanges(User.Identity.GetUserName());

                OnCrudOperation(new ProductEventArgs(product, CrudEventEnumStatus.Create));

                if (!string.IsNullOrWhiteSpace(Request.QueryString["createNext"]))
                {
                    if (Request.QueryString["createNext"] == "true")
                    {
                        TempData["Created"] = true;
                        TempData["Alert"] = "Berhasil menambahkan Product";
                        TempData["AlertClass"] = "success";

                        return RedirectToAction("Create");
                    }
                }

                return RedirectToAction("Details", new { id = product.Id});
            }

            TempData["Alert"] = "Gagal menambahkan Product. Harap periksa kembali data yang anda input.";
            TempData["AlertClass"] = "danger";

            return View(product);
        }

        [PermissionAuthorization("crud_master_data")]
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            ViewBag.Id = id;

            if (product == null)
            {
                return HttpNotFound();
            }

            return View(product);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [PermissionAuthorization("crud_master_data")]
        public ActionResult Edit(Product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;

                db.SaveChanges(User.Identity.GetUserName());

                OnCrudOperation(new ProductEventArgs(product, CrudEventEnumStatus.Update));

                TempData["Alert"] = "Berhasil menyimpan perubahan Product";
                TempData["AlertClass"] = "success";

                return RedirectToAction("Details", new { id = product.Id});
            }
            ViewBag.Id = product.Id;

            TempData["Alert"] = "Gagal melakukan perubahan Product. Harap periksa kembali data yang anda masukkan.";
            TempData["AlertClass"] = "danger";

            return View(product);
        }

        [PermissionAuthorization("crud_master_data")]
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Product product = db.Products.Find(id);
            ViewBag.Id = id;

            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [PermissionAuthorization("crud_master_data")]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Product product = db.Products.Find(id);
            ViewBag.Id = id;
            db.Products.Remove(product);
            db.SaveChanges(User.Identity.GetUserName());
            OnCrudOperation(new ProductEventArgs(product, CrudEventEnumStatus.Delete));
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

App/Controllers/WebApi/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Linq.Dynamic;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Http.Description;
using AutoMapper;
using AutoMapper.QueryableExtensions;
using Kendo.DynamicLinq;
using Newtonsoft.Json;
using Domain.Models;
using App.DAL;
using App.Enums;
using App.Helper;
using Domain.Models.ViewModels;
using Microsoft.AspNet.Identity;

namespace App.Controllers.WebApi
{
    public class CategoriesControllerEventArgs : EventArgs
    {
        public readonly Category After;
        public readonly CrudEventEnumStatus Status;

        public CategoriesControllerEventArgs(Category after, CrudEventEnumStatus status)
        {
            this.After = after;
            this.Status = status;
        }
    }

    public class CategoriesController : ApiController
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public static event EventHandler<CategoriesControllerEventArgs> AfterCall;

        protected virtual void OnCrudOperation(CategoriesControllerEventArgs e)
        {
            if (AfterCall != null)
            {
                AfterCall(this, e);
            }
        }

        // GET: api/Categories
        public DataSourceResult GetCategories(HttpRequestMessage requestMessage)
        {
            DataSourceRequest request =
                JsonConvert.DeserializeObject<DataSourceRequest>(requestMessage.RequestUri.ParseQueryString().GetValues("q")[0]);

            if (request.Filter != null && !request.Filter.Filters.Any())
            {
                request.Filter = null;
            }
            else
            {
                request.Filter.ToCustomExpression();
            }

            var result = db.Categories.Include(x => x.Products).AsQueryable();

            return result
                .OrderBy(x => x.Id)
                .Project()
                .To<CategoryViewModel>()
                .ToDataSourceResult(request.Take, request.Skip, request.Sort, request.Filter);
        }

        // GET: api/Categories/5
        [ResponseType(typeof(CategoryViewModel))]
        public IHttpActionResult GetCategory(int id)
        {
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return NotFound();
            }

            return Ok(Mapper.Map<Category, CategoryViewModel>(category));
        }

        // PUT: api/Categories/5
        [ResponseType(typeof(void))]
        public IHttpActionResult PutCategory(int id, CategoryViewModel category)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (id != category.Id)
            {
                return BadRequest();
            }

            var tempcategory = category.ToEntity();

            db.Entry(tempcategory).State = EntityState.Modified;

            try
            {
                db.SaveChanges(User.Identity.GetUserName());
                OnCrudOperation(new CategoriesControllerEventArgs(tempcategory, CrudEventEnumStatus.Update));
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!CategoryExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return StatusCode(HttpStatusCode.NoContent);
        }

        // POST: api/Categories
        [ResponseType(typeof(CategoryViewModel))]
        public IHttpActionResult PostCategory(CategoryViewModel category)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            var tempcategory = category.ToEntity();

            db.Categories.Add(tempcategory);
            db.SaveChanges(User.Identity.GetUserName());
            OnCrudOperation(new CategoriesControllerEventArgs(tempcategory, CrudEventEnumStatus.Create));

            return CreatedAtRoute("DefaultApi", new { id = category.Id }, 
                    Mapper.Map<Category, CategoryViewModel>(tempcategory));
        }

        // DELETE: api/Categories/5
        [ResponseType(typeof(CategoryViewModel))]
        public IHttpActionResult DeleteCategory(int id)
        {
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return NotFound();
            }

            db.Categories.Remove(category);
            db.SaveChanges(User.Identity.GetUserName());
            OnCrudOperation(new CategoriesControllerEventArgs(category, CrudEventEnumStatus.Delete));

            return Ok(Mapper.Map<Category, CategoryViewModel>(category));
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private bool CategoryExists(int id)
        {
            return db.Categories.Count(e => e.Id == id) > 0;
        }
    }
}

App/Views/Category/Create.cshtml
@model Domain.Models.Category

@{
    ViewBag.Title = "Create";
    var webApiUrl = System.Configuration.ConfigurationManager.AppSettings["webApiUrl"];
}

<div class="panel">
    <div class="panel-header border-bottom">
        <h2>
            <span class="fa fa-plus-circle"></span> <strong>Category - Create</strong>
        </h2>
    </div>
    <div class="panel-content">
    @using (Html.BeginForm("Create", "Category", FormMethod.Post, new { @id = "formCreate" })) 
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { @class = "form-control form-white" })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
            </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Description, new { @class = "form-control form-white" })
                            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                        </div>
            </div>

                <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="k-button" /> &nbsp; <button type="submit" value="true" name="createNext" class="k-button k-primary">Save and create next</button>
                </div>
            </div>
        </div>
    }
    </div>
    <div class="panel-footer">
        <p class="pull-right">
            @Html.ActionLink("Category List", "Index")
            @if (Request.UrlReferrer != null)
            {
                @: | <a class="bottomNav" onclick="history.go(-1); return false;" href="#">Back</a><br/>
            }
        </p>
        <div class="clearfix"></div>
    </div>
</div>

@section scripts{
    <script src="~/Scripts/jquery.validate.min.js" type="text/javascript"></script>
    <script type="text/javascript">
        $("#formCreate").validate({
            rules: {
                Name: {
                    required: true,
                },
                Description: {
                },
            }
        });

        $(".kendo-dropdownlist").kendoDropDownList({
            filter: "contains"
        });

        $("button[name='createNext']").click(function (e) {
            var url = $("#formCreate").attr("action") + "?createNext=true";
            $("#formCreate").attr("action", url);
        });

        $(".kendo-datetimepicker").kendoDateTimePicker({
            format: "yyyy-MM-dd HH:mm"
        });
        $(".richtextbox").kendoEditor({
            tools: [
                "bold",
                "italic",
                "underline",
                "strikethrough",
                "justifyLeft",
                "justifyCenter",
                "justifyRight",
                "justifyFull",
                "insertUnorderedList",
                "insertOrderedList",
                "indent",
                "outdent",
                "createLink",
                "unlink",
                "insertImage",
                "insertFile",
                "subscript",
                "superscript",
                "createTable",
                "addRowAbove",
                "addRowBelow",
                "addColumnLeft",
                "addColumnRight",
                "deleteRow",
                "deleteColumn",
                "viewHtml",
                "formatting",
                "cleanFormatting",
                "fontName",
                "fontSize",
                "foreColor",
                "backColor"
            ],
            encoded: false
        });
    </script>
}

App/Views/Category/Details.cshtml
@model Domain.Models.Category

@{
    ViewBag.Title = "Details";

    var webApiUrl = System.Configuration.ConfigurationManager.AppSettings["webApiUrl"];
}

<div class="panel">
    <div class="panel-header border-bottom">
        <h2>
            <span class="fa fa-info-circle"></span> <strong>Category - Details</strong>
        </h2>
    </div>
    <div class="panel-content">
        <dl class="dl-horizontal">
                        <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
                    <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>
                    <dt>
                @Html.DisplayNameFor(model => model.CreatedAt)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CreatedAt)
            </dd>
                    <dt>
                @Html.DisplayNameFor(model => model.LastUpdateTime)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.LastUpdateTime)
            </dd>
            </dl>
            <div id="tabstrip">
            <ul>
                    <li class="k-state-active">
                    Products
                </li>
                    <li class="">
                    Logs
                </li>
                </ul>
                <div id="grid-Products"></div>
                <div id="grid-logs"></div>
            </div>
        <div style="height: 20px;"></div>
        </div>
    <div class="panel-footer">
        <p class="pull-right">
            @Html.ActionLink("Edit", "Edit", new { id = ViewBag.Id }) |
            @Html.ActionLink("Category List", "Index")
            @if (Request.UrlReferrer != null)
            {
                @: | <a class="bottomNav" onclick="history.go(-1); return false;" href="#">Back</a><br />
            }
        </p>
        <div class="clearfix"></div>
    </div>
</div>

@section scripts{
    <script type="text/javascript">
        $(document).ready(function() {
            $("#tabstrip").kendoTabStrip({
                animation:  {
                    open: {
                        effects: "fadeIn"
                    }
                }
            });
        });
        var dsProducts = new kendo.data.DataSource({
            type: "json",
            transport: {
                read: {
                    url: "@(webApiUrl)Products",
                    dataType: "json",
                    contentType: "application/json"
                },
                parameterMap: function (options, operation) {
                    if (operation === "destroy") {
                        return null;
                    } else if (operation !== "read" && options.models) {
                        return { models: kendo.stringify(options.models) };
                    } else {
                        return "q=" + JSON.stringify(options);
                    }
                }
            },
            schema: {
                data: "Data",
                total: "Total",
                model: {
                    id: 'Id'
                }
            },
            filter: {
                field: "CategoryId",
                operator: "eq",
                value: parseInt("@ViewBag.Id")
            },
            serverFiltering: true,
            serverPaging: true,
            serverSorting: true,
            pageSize: 10
        });

        $("#grid-Products").kendoGrid({
            dataSource: dsProducts,
            dataBound: gridDataBound,
            noDataMessage: 'Currently no Products available',
            sortable: true,
            filterable: {
                mode: "row"
            },
            pageable:{
                refresh: true,
                pageSizes: true,
                buttonCount: 5
            },
            groupable: true,
            columns: [
                "Name",
                "Picture",
                "Price",
                "Quantity",
                {
                    command: [
                        {
                            name: 'Details',
                            click: function (data) {
                                var dataItem = this.dataItem($(data.currentTarget).closest("tr"));
                                window.location = "@Url.Action("Details", "Product")/" + dataItem.Id;
                            },
                            text: "<button class='btn btn-default btn-transparent btn-sm p-0' title='Details'><span class='fa fa-search'></span></button>"
                        }
                    ],
                    width: 100
                }
            ]
        });

        var dsLogs = new kendo.data.DataSource({
            type: "json",
            transport: {
                read: {
                    url: "@(webApiUrl)logs/Categories/@ViewBag.Id",
                    dataType: "json",
                    contentType: "application/json"
                },
                parameterMap: function(options, operation) {
                    if (operation === "destroy") {
                        return null;
                    } else if (operation !== "read" && options.models) {
                        return { models: kendo.stringify(options.models) };
                    } else {
                        return "q=" + JSON.stringify(options);
                    }
                }
            },
            schema: {
                data: "Data",
                total: "Total",
                model: {
                    id: 'Id',
                    fields: {
                        EventDateUTC: {
                            type: "date"
                        }
                    }
                }
            },
            serverFiltering: true,
            serverPaging: true,
            serverSorting: true,
            pageSize: 10
        });

        $("#grid-logs").kendoGrid({
            dataSource: dsLogs,
            sortable: true,
            filterable: {
                mode: "row"
            },
            pageable: {
                refresh: true,
                pageSizes: true,
                buttonCount: 5
            },
            groupable: true,
            columns: [
                {
                    field: "EventType",
                    title: "Type"
                },
                {
                    field: "EventDateUTC",
                    title: "Change Date",
                    format: "{0: yyyy-MM-dd HH:mm:ss}"
                },
                {
                    field: "ColumnName",
                    title: "Column"
                },
                {
                    field: "OriginalValue",
                    title: "Original"
                },
                {
                    field: "NewValue",
                    title: "New"
                },
                {
                    field: "UserName",
                    title: "By"
                }
            ]
        });
    </script>
}

App/Views/Category/Edit.cshtml
@model Domain.Models.Category

@{
    ViewBag.Title = "Edit";

    var webApiUrl = System.Configuration.ConfigurationManager.AppSettings["webApiUrl"];
}
<div class="panel">
    <div class="panel-header border-bottom">
        <h2>
            <span class="fa fa-edit"></span> <strong>Category - Edit</strong>
        </h2>
    </div>
    <div class="panel-content">
        @using (Html.BeginForm("Edit", "Category", FormMethod.Post, new { @id = "formEdit" }))
        {
            @Html.AntiForgeryToken()
    
            <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                @Html.HiddenFor(model => model.Id)

                        <div class="form-group">
                            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Name, new { @class = "form-control form-white" })
                                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                    </div>
                </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Description, new { @class = "form-control form-white" })
                                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                                    </div>
                </div>

                        @Html.HiddenFor(model => model.CreatedAt)
                        @Html.HiddenFor(model => model.LastUpdateTime)
                        <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="k-button k-primary" />
                    </div>
                </div>
            </div>
        }
    </div>
    <div class="panel-footer">
        <p class="pull-right">
            @Html.ActionLink("Details", "Details", new { id = ViewBag.Id }) |
            @Html.ActionLink("Category List", "Index")
            @if (Request.UrlReferrer != null)
            {
                @: | <a class="bottomNav" onclick="history.go(-1); return false;" href="#">Back</a><br/>
            }
        </p>
        <div class="clearfix"></div>
    </div>
</div>

@section scripts{
    <script src="~/Scripts/jquery.validate.min.js" type="text/javascript"></script>
    <script type="text/javascript">
        $("#formEdit").validate({
            rules: {
                Name: {
                    required: true,
                },
                Description: {
                },
            }
        });
    $(".richtextbox").kendoEditor({
        tools: [
            "bold",
            "italic",
            "underline",
            "strikethrough",
            "justifyLeft",
            "justifyCenter",
            "justifyRight",
            "justifyFull",
            "insertUnorderedList",
            "insertOrderedList",
            "indent",
            "outdent",
            "createLink",
            "unlink",
            "insertImage",
            "insertFile",
            "subscript",
            "superscript",
            "createTable",
            "addRowAbove",
            "addRowBelow",
            "addColumnLeft",
            "addColumnRight",
            "deleteRow",
            "deleteColumn",
            "viewHtml",
            "formatting",
            "cleanFormatting",
            "fontName",
            "fontSize",
            "foreColor",
            "backColor"
        ],
        encoded: false
    });
        $(".kendo-datetimepicker").kendoDateTimePicker({
            format: "yyyy-MM-dd HH:mm"
        });
    </script>
}