App/Controllers/PermissionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Domain.Infrastructure;
using App.DAL;
using App.Enums;
using Microsoft.AspNet.Identity;

namespace App.Controllers
{
    public class PermissionEventArgs : EventArgs
    {
        public readonly Permission After;
        public readonly CrudEventEnumStatus Status;

        public PermissionEventArgs(Permission after, CrudEventEnumStatus status)
        {
            this.After = after;
            this.Status = status;
        }
    }

    public class PermissionController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public static event EventHandler<PermissionEventArgs> AfterCall;

        protected virtual void OnCrudOperation(PermissionEventArgs e)
        {
            if (AfterCall != null)
            {
                AfterCall(this, e);
            }
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Permission permission = db.Permissions.Find(id);
            ViewBag.Id = id;
            if (permission == null)
            {
                return HttpNotFound();
            }
            return View(permission);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Permission permission)
        {
            if (ModelState.IsValid)
            {
                permission.Id = Guid.NewGuid();
                db.Permissions.Add(permission);

                db.SaveChanges(User.Identity.GetUserName());

                OnCrudOperation(new PermissionEventArgs(permission, CrudEventEnumStatus.Create));

                if (!string.IsNullOrWhiteSpace(Request.QueryString["createNext"]))
                {
                    if (Request.QueryString["createNext"] == "true")
                    {
                        TempData["Created"] = true;
                        TempData["Alert"] = "Berhasil menambahkan Permission";
                        TempData["AlertClass"] = "success";

                        return RedirectToAction("Create");
                    }
                }

                return RedirectToAction("Details", new { id = permission.Id});
            }

            TempData["Alert"] = "Gagal menambahkan Permission. Harap periksa kembali data yang anda input.";
            TempData["AlertClass"] = "danger";

            return View(permission);
        }

        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Permission permission = db.Permissions.Find(id);
            ViewBag.Id = id;

            if (permission == null)
            {
                return HttpNotFound();
            }

            return View(permission);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Permission permission)
        {
            if (ModelState.IsValid)
            {
                db.Entry(permission).State = EntityState.Modified;

                db.SaveChanges(User.Identity.GetUserName());

                OnCrudOperation(new PermissionEventArgs(permission, CrudEventEnumStatus.Update));

                TempData["Alert"] = "Berhasil menyimpan perubahan Permission";
                TempData["AlertClass"] = "success";

                return RedirectToAction("Details", new { id = permission.Id});
            }
            ViewBag.Id = permission.Id;

            TempData["Alert"] = "Gagal melakukan perubahan Permission. Harap periksa kembali data yang anda masukkan.";
            TempData["AlertClass"] = "danger";

            return View(permission);
        }

        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Permission permission = db.Permissions.Find(id);
            ViewBag.Id = id;

            if (permission == null)
            {
                return HttpNotFound();
            }
            return View(permission);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Permission permission = db.Permissions.Find(id);
            ViewBag.Id = id;
            db.Permissions.Remove(permission);
            db.SaveChanges(User.Identity.GetUserName());
            OnCrudOperation(new PermissionEventArgs(permission, CrudEventEnumStatus.Delete));
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

App/Controllers/RolePermissionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Domain.Infrastructure;
using App.DAL;
using App.Enums;
using App.Infrastructure;
using Microsoft.AspNet.Identity;

namespace App.Controllers
{
    [PermissionAuthorization("administrator_only")]
    public class RolePermissionEventArgs : EventArgs
    {
        public readonly RolePermission After;
        public readonly CrudEventEnumStatus Status;

        public RolePermissionEventArgs(RolePermission after, CrudEventEnumStatus status)
        {
            this.After = after;
            this.Status = status;
        }
    }

    public class RolePermissionController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public static event EventHandler<RolePermissionEventArgs> AfterCall;

        protected virtual void OnCrudOperation(RolePermissionEventArgs e)
        {
            if (AfterCall != null)
            {
                AfterCall(this, e);
            }
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RolePermission rolePermission = db.RolePermissions.Find(id);
            ViewBag.Id = id;
            if (rolePermission == null)
            {
                return HttpNotFound();
            }
            return View(rolePermission);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RolePermission rolePermission)
        {
            if (ModelState.IsValid)
            {
                rolePermission.Id = Guid.NewGuid();
                db.RolePermissions.Add(rolePermission);

                db.SaveChanges(User.Identity.GetUserName());

                OnCrudOperation(new RolePermissionEventArgs(rolePermission, CrudEventEnumStatus.Create));

                if (!string.IsNullOrWhiteSpace(Request.QueryString["createNext"]))
                {
                    if (Request.QueryString["createNext"] == "true")
                    {
                        TempData["Created"] = true;
                        TempData["Alert"] = "Berhasil menambahkan RolePermission";
                        TempData["AlertClass"] = "success";

                        return RedirectToAction("Create");
                    }
                }

                return RedirectToAction("Details", new { id = rolePermission.Id});
            }

            TempData["Alert"] = "Gagal menambahkan RolePermission. Harap periksa kembali data yang anda input.";
            TempData["AlertClass"] = "danger";

            return View(rolePermission);
        }

        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RolePermission rolePermission = db.RolePermissions.Find(id);
            ViewBag.Id = id;

            if (rolePermission == null)
            {
                return HttpNotFound();
            }

            return View(rolePermission);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(RolePermission rolePermission)
        {
            if (ModelState.IsValid)
            {
                db.Entry(rolePermission).State = EntityState.Modified;

                db.SaveChanges(User.Identity.GetUserName());

                OnCrudOperation(new RolePermissionEventArgs(rolePermission, CrudEventEnumStatus.Update));

                TempData["Alert"] = "Berhasil menyimpan perubahan RolePermission";
                TempData["AlertClass"] = "success";

                return RedirectToAction("Details", new { id = rolePermission.Id});
            }
            ViewBag.Id = rolePermission.Id;

            TempData["Alert"] = "Gagal melakukan perubahan RolePermission. Harap periksa kembali data yang anda masukkan.";
            TempData["AlertClass"] = "danger";

            return View(rolePermission);
        }

        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            RolePermission rolePermission = db.RolePermissions.Find(id);
            ViewBag.Id = id;

            if (rolePermission == null)
            {
                return HttpNotFound();
            }
            return View(rolePermission);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            RolePermission rolePermission = db.RolePermissions.Find(id);
            ViewBag.Id = id;
            db.RolePermissions.Remove(rolePermission);
            db.SaveChanges(User.Identity.GetUserName());
            OnCrudOperation(new RolePermissionEventArgs(rolePermission, CrudEventEnumStatus.Delete));
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

App/Controllers/WebApi/RolePermissionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Linq.Dynamic;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Http.Description;
using AutoMapper;
using AutoMapper.QueryableExtensions;
using Kendo.DynamicLinq;
using Newtonsoft.Json;
using Domain.Infrastructure;
using App.DAL;
using App.Enums;
using App.Helper;
using Domain.Models.ViewModels;
using Microsoft.AspNet.Identity;

namespace App.Controllers.WebApi
{
    public class RolePermissionsControllerEventArgs : EventArgs
    {
        public readonly RolePermission After;
        public readonly CrudEventEnumStatus Status;

        public RolePermissionsControllerEventArgs(RolePermission after, CrudEventEnumStatus status)
        {
            this.After = after;
            this.Status = status;
        }
    }

    public class RolePermissionsController : ApiController
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public static event EventHandler<RolePermissionsControllerEventArgs> AfterCall;

        protected virtual void OnCrudOperation(RolePermissionsControllerEventArgs e)
        {
            if (AfterCall != null)
            {
                AfterCall(this, e);
            }
        }

        // GET: api/RolePermissions
        public DataSourceResult GetRolePermissions(HttpRequestMessage requestMessage)
        {
            DataSourceRequest request =
                JsonConvert.DeserializeObject<DataSourceRequest>(requestMessage.RequestUri.ParseQueryString().GetValues("q")[0]);

            if (request.Filter != null && !request.Filter.Filters.Any())
            {
                request.Filter = null;
            }
            else
            {
                request.Filter.ToCustomExpression();
            }

            var result = db.RolePermissions.Include(x => x.Permission).Include(x => x.Role).AsQueryable();

            return result
                .OrderBy(x => x.Id)
                .Project()
                .To<RolePermissionViewModel>()
                .ToDataSourceResult(request.Take, request.Skip, request.Sort, request.Filter);
        }

        // GET: api/RolePermissions/5
        [ResponseType(typeof(RolePermissionViewModel))]
        public IHttpActionResult GetRolePermission(Guid id)
        {
            RolePermission rolePermission = db.RolePermissions.Find(id);
            if (rolePermission == null)
            {
                return NotFound();
            }

            return Ok(Mapper.Map<RolePermission, RolePermissionViewModel>(rolePermission));
        }

        // PUT: api/RolePermissions/5
        [ResponseType(typeof(void))]
        public IHttpActionResult PutRolePermission(Guid id, RolePermissionViewModel rolePermission)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (id != rolePermission.Id)
            {
                return BadRequest();
            }

            var temprolePermission = rolePermission.ToEntity();

            db.Entry(temprolePermission).State = EntityState.Modified;

            try
            {
                db.SaveChanges(User.Identity.GetUserName());
                OnCrudOperation(new RolePermissionsControllerEventArgs(temprolePermission, CrudEventEnumStatus.Update));
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!RolePermissionExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return StatusCode(HttpStatusCode.NoContent);
        }

        // POST: api/RolePermissions
        [ResponseType(typeof(RolePermissionViewModel))]
        public IHttpActionResult PostRolePermission([FromBody] IList<RolePermissionViewModel> rolePermissions)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (rolePermissions.Count == 0)
            {
                return BadRequest();
            }

            var ids = new List<RolePermissionViewModel>();

            foreach (var rolePermission in rolePermissions)
            {
                var temp = rolePermission.ToEntity();

                db.RolePermissions.Add(temp);
                db.SaveChanges(User.Identity.GetUserName());

                ids.Add(Mapper.Map<RolePermission, RolePermissionViewModel>(temp));

                OnCrudOperation(new RolePermissionsControllerEventArgs(temp, CrudEventEnumStatus.Create));
            }

            return Ok(ids);
        }

        // DELETE: api/RolePermissions/5
        [ResponseType(typeof(RolePermissionViewModel))]
        public IHttpActionResult DeleteRolePermission(Guid id)
        {
            RolePermission rolePermission = db.RolePermissions.Find(id);
            if (rolePermission == null)
            {
                return NotFound();
            }

            db.RolePermissions.Remove(rolePermission);
            db.SaveChanges(User.Identity.GetUserName());
            OnCrudOperation(new RolePermissionsControllerEventArgs(rolePermission, CrudEventEnumStatus.Delete));

            return Ok(Mapper.Map<RolePermission, RolePermissionViewModel>(rolePermission));
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private bool RolePermissionExists(Guid id)
        {
            return db.RolePermissions.Count(e => e.Id == id) > 0;
        }
    }
}

App/Views/RolePermission/Create.cshtml
@model Domain.Infrastructure.RolePermission

@{
    ViewBag.Title = "Create";
    var webApiUrl = System.Configuration.ConfigurationManager.AppSettings["webApiUrl"];
}

<div class="panel">
    <div class="panel-header border-bottom">
        <h2>
            <span class="fa fa-plus-circle"></span> <strong>RolePermission - Create</strong>
        </h2>
    </div>
    <div class="panel-content">
        @using (Html.BeginForm("Create", "RolePermission", FormMethod.Post, new { @id = "formCreate" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.RoleId, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("RoleId", new SelectList(new List<string>()), htmlAttributes: new { @class = "form-control kendo-dropdownlist", @id = "RoleId" })
                        @Html.ValidationMessageFor(model => model.RoleId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.PermissionId, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("PermissionId", new SelectList(new List<string>()), htmlAttributes: new { @class = "form-control kendo-dropdownlist", @id = "PermissionId" })
                        @Html.ValidationMessageFor(model => model.PermissionId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="k-button" /> &nbsp; <button type="submit" value="true" name="createNext" class="k-button k-primary">Save and create next</button>
                    </div>
                </div>
            </div>
        }
    </div>
    <div class="panel-footer">
        <p class="pull-right">
            @Html.ActionLink("RolePermission List", "Index")
            @if (Request.UrlReferrer != null)
            {
                @: | <a class="bottomNav" onclick="history.go(-1); return false;" href="#">Back</a><br />
            }
        </p>
        <div class="clearfix"></div>
    </div>
</div>

@section scripts{
    <script src="~/Scripts/jquery.validate.min.js" type="text/javascript"></script>
    <script type="text/javascript">
        $("#formCreate").validate({
            rules: {
                RoleId: {
                    required: true,
                },
                PermissionId: {
                    required: true,
                },
            }
        });

        $(".kendo-dropdownlist").kendoDropDownList({
            filter: "contains"
        });

        $("button[name='createNext']").click(function (e) {
            var url = $("#formCreate").attr("action") + "?createNext=true";
            $("#formCreate").attr("action", url);
        });

        var dsRoleId = new kendo.data.DataSource({
            type: "json",
            transport: {
                read: {
                    url: "@(webApiUrl)Roles",
                    dataType: "json",
                    contentType: "application/json",
                },
                parameterMap: function (options, operation) {
                    if (operation === "destroy") {
                        return null;
                    } else if (operation !== "read" && options.models) {
                        return { models: kendo.stringify(options.models) };
                    } else {
                        return "q=" + JSON.stringify(options);
                    }
                }
            },
            schema: {
                data: "Data",
                total: "Total",
                model: {
                    id: 'Id',
                    fields: {

                    }
                }
            },
            serverFiltering: true,
            serverPaging: true,
            pageSize: 7
        });

        $("#RoleId").kendoDropDownList({
            filter: "contains",
            dataSource: dsRoleId,
            dataTextField: "Name",
            dataValueField: "Id",
        });

        var dsPermissionId = new kendo.data.DataSource({
            type: "json",
            transport: {
                read: {
                    url: "@(webApiUrl)Permissions",
                    dataType: "json",
                    contentType: "application/json",
                },
                parameterMap: function (options, operation) {
                    if (operation === "destroy") {
                        return null;
                    } else if (operation !== "read" && options.models) {
                        return { models: kendo.stringify(options.models) };
                    } else {
                        return "q=" + JSON.stringify(options);
                    }
                }
            },
            schema: {
                data: "Data",
                total: "Total",
                model: {
                    id: 'Id',
                    fields: {

                    }
                }
            },
            serverFiltering: true,
            serverPaging: true,
            pageSize: 7
        });

        $("#PermissionId").kendoDropDownList({
            filter: "contains",
            dataSource: dsPermissionId,
            dataTextField: "Name",
            dataValueField: "Id",
        });

        $(".kendo-datetimepicker").kendoDateTimePicker({
            format: "yyyy-MM-dd HH:mm"
        });
    </script>
}

App/Views/RolePermission/Details.cshtml
@model Domain.Infrastructure.RolePermission

@{
    ViewBag.Title = "Details";

    var webApiUrl = System.Configuration.ConfigurationManager.AppSettings["webApiUrl"];
}

<div class="panel">
    <div class="panel-header border-bottom">
        <h2>
            <span class="fa fa-info-circle"></span> <strong>RolePermission - Details</strong>
        </h2>
    </div>
    <div class="panel-content">
        <dl class="dl-horizontal">
                    <dt>
                @Html.DisplayNameFor(model => model.Permission)
            </dt>

            <dd>
                <a href="@Url.Action("Details", "Permission", new { id = Model.Permission.Id })" >@Model.Permission.Name</a>
            </dd>
                    <dt>
                @Html.DisplayNameFor(model => model.Role)
            </dt>

            <dd>
                <a href="@Url.Action("Details", "ApplicationRole", new { id = Model.Role.Id })" >@Model.Role.Name</a>
            </dd>
                    <dt>
                @Html.DisplayNameFor(model => model.CreatedAt)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CreatedAt)
            </dd>
                    <dt>
                @Html.DisplayNameFor(model => model.LastUpdateTime)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.LastUpdateTime)
            </dd>
            </dl>
            <div id="tabstrip">
            <ul>
                    <li class="k-state-active">
                    Logs
                </li>
                </ul>
                <div id="grid-logs"></div>
            </div>
        <div style="height: 20px;"></div>
        </div>
    <div class="panel-footer">
        <p class="pull-right">
            @Html.ActionLink("Edit", "Edit", new { id = ViewBag.Id }) |
            @Html.ActionLink("RolePermission List", "Index")
            @if (Request.UrlReferrer != null)
            {
                @: | <a class="bottomNav" onclick="history.go(-1); return false;" href="#">Back</a><br />
            }
        </p>
        <div class="clearfix"></div>
    </div>
</div>

@section scripts{
    <script type="text/javascript">
        $(document).ready(function() {
            $("#tabstrip").kendoTabStrip({
                animation:  {
                    open: {
                        effects: "fadeIn"
                    }
                }
            });
        });
        var dsLogs = new kendo.data.DataSource({
            type: "json",
            transport: {
                read: {
                    url: "@(webApiUrl)logs/RolePermissions/@ViewBag.Id",
                    dataType: "json",
                    contentType: "application/json"
                },
                parameterMap: function(options, operation) {
                    if (operation === "destroy") {
                        return null;
                    } else if (operation !== "read" && options.models) {
                        return { models: kendo.stringify(options.models) };
                    } else {
                        return "q=" + JSON.stringify(options);
                    }
                }
            },
            schema: {
                data: "Data",
                total: "Total",
                model: {
                    id: 'Id',
                    fields: {
                        EventDateUTC: {
                            type: "date"
                        }
                    }
                }
            },
            serverFiltering: true,
            serverPaging: true,
            serverSorting: true,
            pageSize: 10
        });

        $("#grid-logs").kendoGrid({
            dataSource: dsLogs,
            sortable: true,
            filterable: {
                mode: "row"
            },
            pageable: {
                refresh: true,
                pageSizes: true,
                buttonCount: 5
            },
            groupable: true,
            columns: [
                {
                    field: "EventType",
                    title: "Type"
                },
                {
                    field: "EventDateUTC",
                    title: "Change Date",
                    format: "{0: yyyy-MM-dd HH:mm:ss}"
                },
                {
                    field: "ColumnName",
                    title: "Column"
                },
                {
                    field: "OriginalValue",
                    title: "Original"
                },
                {
                    field: "NewValue",
                    title: "New"
                },
                {
                    field: "UserName",
                    title: "By"
                }
            ]
        });
    </script>
}