App/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Domain.Infrastructure;
using App.DAL;
using App.Enums;
using App.Infrastructure;
using Microsoft.AspNet.Identity;

namespace App.Controllers
{
    public class MenuEventArgs : EventArgs
    {
        public readonly Menu After;
        public readonly CrudEventEnumStatus Status;

        public MenuEventArgs(Menu after, CrudEventEnumStatus status)
        {
            this.After = after;
            this.Status = status;
        }
    }

    public class MenuController : BaseUserController
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public static event EventHandler<MenuEventArgs> AfterCall;

        protected virtual void OnCrudOperation(MenuEventArgs e)
        {
            if (AfterCall != null)
            {
                AfterCall(this, e);
            }
        }

        [PermissionAuthorization("read_master_data")]
        public ActionResult Index()
        {
            return View();
        }

        [PermissionAuthorization("read_master_data")]
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Menu menu = db.Menus.Find(id);
            ViewBag.Id = id;
            if (menu == null)
            {
                return HttpNotFound();
            }
            return View(menu);
        }

        [PermissionAuthorization("crud_master_data")]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [PermissionAuthorization("crud_master_data")]
        public ActionResult Create(Menu menu)
        {
            if (ModelState.IsValid)
            {
                menu.Id = Guid.NewGuid();
                db.Menus.Add(menu);

                db.SaveChanges(User.Identity.GetUserName());

                OnCrudOperation(new MenuEventArgs(menu, CrudEventEnumStatus.Create));

                if (!string.IsNullOrWhiteSpace(Request.QueryString["createNext"]))
                {
                    if (Request.QueryString["createNext"] == "true")
                    {
                        TempData["Created"] = true;
                        TempData["Alert"] = "Berhasil menambahkan Menu";
                        TempData["AlertClass"] = "success";

                        return RedirectToAction("Create");
                    }
                }

                return RedirectToAction("Details", new { id = menu.Id});
            }

            TempData["Alert"] = "Gagal menambahkan Menu. Harap periksa kembali data yang anda input.";
            TempData["AlertClass"] = "danger";

            return View(menu);
        }

        [PermissionAuthorization("crud_master_data")]
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Menu menu = db.Menus.Find(id);
            ViewBag.Id = id;

            if (menu == null)
            {
                return HttpNotFound();
            }

            return View(menu);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [PermissionAuthorization("crud_master_data")]
        public ActionResult Edit(Menu menu)
        {
            if (ModelState.IsValid)
            {
                db.Entry(menu).State = EntityState.Modified;

                db.SaveChanges(User.Identity.GetUserName());

                OnCrudOperation(new MenuEventArgs(menu, CrudEventEnumStatus.Update));

                TempData["Alert"] = "Berhasil menyimpan perubahan Menu";
                TempData["AlertClass"] = "success";

                return RedirectToAction("Details", new { id = menu.Id});
            }
            ViewBag.Id = menu.Id;

            TempData["Alert"] = "Gagal melakukan perubahan Menu. Harap periksa kembali data yang anda masukkan.";
            TempData["AlertClass"] = "danger";

            return View(menu);
        }

        [ChildActionOnly]
        [AllowAnonymous]
        public ActionResult RenderMenu()
        {
            var userId = User.Identity.GetUserId();
            var roles = AppUserManager.GetRoles(userId);

            var menus = db.Menus.AsQueryable();

            foreach (var role in roles)
            {
                var roleId = AppRoleManager.FindByName(role);
                menus = menus.Where(x => x.RoleMenus.Any(r => r.RoleId == roleId.Id));
            }

            menus = menus.OrderBy(x => x.SortOrder);

            return PartialView("_RenderMenu", menus.ToList());
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

App/Controllers/RoleMenuController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Domain.Infrastructure;
using App.DAL;
using App.Enums;
using App.Infrastructure;
using Microsoft.AspNet.Identity;

namespace App.Controllers
{
    [PermissionAuthorization("administrator_only")]
    public class RoleMenuEventArgs : EventArgs
    {
        public readonly RoleMenu After;
        public readonly CrudEventEnumStatus Status;

        public RoleMenuEventArgs(RoleMenu after, CrudEventEnumStatus status)
        {
            this.After = after;
            this.Status = status;
        }
    }

    public class RoleMenuController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public static event EventHandler<RoleMenuEventArgs> AfterCall;

        protected virtual void OnCrudOperation(RoleMenuEventArgs e)
        {
            if (AfterCall != null)
            {
                AfterCall(this, e);
            }
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RoleMenu roleMenu = db.RoleMenus.Find(id);
            ViewBag.Id = id;
            if (roleMenu == null)
            {
                return HttpNotFound();
            }
            return View(roleMenu);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RoleMenu roleMenu)
        {
            if (ModelState.IsValid)
            {
                roleMenu.Id = Guid.NewGuid();
                db.RoleMenus.Add(roleMenu);

                db.SaveChanges(User.Identity.GetUserName());

                OnCrudOperation(new RoleMenuEventArgs(roleMenu, CrudEventEnumStatus.Create));

                if (!string.IsNullOrWhiteSpace(Request.QueryString["createNext"]))
                {
                    if (Request.QueryString["createNext"] == "true")
                    {
                        TempData["Created"] = true;
                        TempData["Alert"] = "Berhasil menambahkan RoleMenu";
                        TempData["AlertClass"] = "success";

                        return RedirectToAction("Create");
                    }
                }

                return RedirectToAction("Details", new { id = roleMenu.Id});
            }

            TempData["Alert"] = "Gagal menambahkan RoleMenu. Harap periksa kembali data yang anda input.";
            TempData["AlertClass"] = "danger";

            return View(roleMenu);
        }

        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RoleMenu roleMenu = db.RoleMenus.Find(id);
            ViewBag.Id = id;

            if (roleMenu == null)
            {
                return HttpNotFound();
            }

            return View(roleMenu);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(RoleMenu roleMenu)
        {
            if (ModelState.IsValid)
            {
                db.Entry(roleMenu).State = EntityState.Modified;

                db.SaveChanges(User.Identity.GetUserName());

                OnCrudOperation(new RoleMenuEventArgs(roleMenu, CrudEventEnumStatus.Update));

                TempData["Alert"] = "Berhasil menyimpan perubahan RoleMenu";
                TempData["AlertClass"] = "success";

                return RedirectToAction("Details", new { id = roleMenu.Id});
            }
            ViewBag.Id = roleMenu.Id;

            TempData["Alert"] = "Gagal melakukan perubahan RoleMenu. Harap periksa kembali data yang anda masukkan.";
            TempData["AlertClass"] = "danger";

            return View(roleMenu);
        }

        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            RoleMenu roleMenu = db.RoleMenus.Find(id);
            ViewBag.Id = id;

            if (roleMenu == null)
            {
                return HttpNotFound();
            }
            return View(roleMenu);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            RoleMenu roleMenu = db.RoleMenus.Find(id);
            ViewBag.Id = id;
            db.RoleMenus.Remove(roleMenu);
            db.SaveChanges(User.Identity.GetUserName());
            OnCrudOperation(new RoleMenuEventArgs(roleMenu, CrudEventEnumStatus.Delete));
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

App/Controllers/WebApi/MenusController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Linq.Dynamic;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Http.Description;
using AutoMapper;
using AutoMapper.QueryableExtensions;
using Kendo.DynamicLinq;
using Newtonsoft.Json;
using Domain.Infrastructure;
using App.DAL;
using App.Enums;
using App.Helper;
using Domain.Models.ViewModels;
using Microsoft.AspNet.Identity;

namespace App.Controllers.WebApi
{
    public class MenusControllerEventArgs : EventArgs
    {
        public readonly Menu After;
        public readonly CrudEventEnumStatus Status;

        public MenusControllerEventArgs(Menu after, CrudEventEnumStatus status)
        {
            this.After = after;
            this.Status = status;
        }
    }

    public class MenusController : ApiController
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public static event EventHandler<MenusControllerEventArgs> AfterCall;

        protected virtual void OnCrudOperation(MenusControllerEventArgs e)
        {
            if (AfterCall != null)
            {
                AfterCall(this, e);
            }
        }

        // GET: api/Menus
        public DataSourceResult GetMenus(HttpRequestMessage requestMessage)
        {
            DataSourceRequest request =
                JsonConvert.DeserializeObject<DataSourceRequest>(requestMessage.RequestUri.ParseQueryString().GetValues("q")[0]);

            if (request.Filter != null && !request.Filter.Filters.Any())
            {
                request.Filter = null;
            }
            else
            {
                request.Filter.ToCustomExpression();
            }

            var result = db.Menus.Include(x => x.RoleMenus).AsQueryable();

            if (!string.IsNullOrWhiteSpace(Helper.Helper.GetQueryStringValue("role", requestMessage)))
            {
                var roleId = Helper.Helper.GetQueryStringValue("role", requestMessage);
                var registeredRoles = db.RoleMenus.Where(x => x.RoleId.ToString() == roleId);

                result = result.Where(x => !registeredRoles.Any(r => r.MenuId == x.Id));
            }

            return result
                .OrderBy(x => x.Name)
                .Project()
                .To<MenuViewModel>()
                .ToDataSourceResult(request.Take, request.Skip, request.Sort, request.Filter);
        }

        // GET: api/Menus/5
        [ResponseType(typeof(MenuViewModel))]
        public IHttpActionResult GetMenu(Guid id)
        {
            Menu menu = db.Menus.Find(id);
            if (menu == null)
            {
                return NotFound();
            }

            return Ok(Mapper.Map<Menu, MenuViewModel>(menu));
        }

        // PUT: api/Menus/5
        [ResponseType(typeof(void))]
        public IHttpActionResult PutMenu(Guid id, MenuViewModel menu)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (id != menu.Id)
            {
                return BadRequest();
            }

            var tempmenu = menu.ToEntity();

            db.Entry(tempmenu).State = EntityState.Modified;

            try
            {
                db.SaveChanges(User.Identity.GetUserName());
                OnCrudOperation(new MenusControllerEventArgs(tempmenu, CrudEventEnumStatus.Update));
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!MenuExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return StatusCode(HttpStatusCode.NoContent);
        }

        // POST: api/Menus
        [ResponseType(typeof(MenuViewModel))]
        public IHttpActionResult PostMenu(MenuViewModel menu)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            var tempmenu = menu.ToEntity();

            db.Menus.Add(tempmenu);
            db.SaveChanges(User.Identity.GetUserName());
            OnCrudOperation(new MenusControllerEventArgs(tempmenu, CrudEventEnumStatus.Create));

            return CreatedAtRoute("DefaultApi", new { id = menu.Id }, 
                    Mapper.Map<Menu, MenuViewModel>(tempmenu));
        }

        // DELETE: api/Menus/5
        [ResponseType(typeof(MenuViewModel))]
        public IHttpActionResult DeleteMenu(Guid id)
        {
            Menu menu = db.Menus.Find(id);
            if (menu == null)
            {
                return NotFound();
            }

            db.Menus.Remove(menu);
            db.SaveChanges(User.Identity.GetUserName());
            OnCrudOperation(new MenusControllerEventArgs(menu, CrudEventEnumStatus.Delete));

            return Ok(Mapper.Map<Menu, MenuViewModel>(menu));
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private bool MenuExists(Guid id)
        {
            return db.Menus.Count(e => e.Id == id) > 0;
        }
    }
}

App/Views/Menu/Create.cshtml
@model Domain.Infrastructure.Menu

@{
    ViewBag.Title = "Create";
    var webApiUrl = System.Configuration.ConfigurationManager.AppSettings["webApiUrl"];
}

<div class="panel">
    <div class="panel-header border-bottom">
        <h2>
            <span class="fa fa-plus-circle"></span> <strong>Menu - Create</strong>
        </h2>
    </div>
    <div class="panel-content">
        @using (Html.BeginForm("Create", "Menu", FormMethod.Post, new { @id = "formCreate" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { @class = "form-control form-white" })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.Title, new { @class = "form-control form-white" })
                        @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Action, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Action, new { @class = "form-control form-white" })
                        @Html.ValidationMessageFor(model => model.Action, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Controller, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Controller, new { @class = "form-control form-white" })
                        @Html.ValidationMessageFor(model => model.Controller, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Url, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Url, new { @class = "form-control form-white" })
                        @Html.ValidationMessageFor(model => model.Url, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Icon, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Icon, new { @class = "form-control form-white" })
                        @Html.ValidationMessageFor(model => model.Icon, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.SortOrder, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.SortOrder, new { @class = "form-control form-white" })
                        @Html.ValidationMessageFor(model => model.SortOrder, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.SubMenu, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.SubMenu, new { @class = "form-control form-white" })
                        @Html.ValidationMessageFor(model => model.SubMenu, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="k-button" /> &nbsp; <button type="submit" value="true" name="createNext" class="k-button k-primary">Save and create next</button>
                    </div>
                </div>
            </div>
        }
    </div>
    <div class="panel-footer">
        <p class="pull-right">
            @Html.ActionLink("Menu List", "Index")
            @if (Request.UrlReferrer != null)
            {
                @: | <a class="bottomNav" onclick="history.go(-1); return false;" href="#">Back</a><br />
            }
        </p>
        <div class="clearfix"></div>
    </div>
</div>

@section scripts{
    <script src="~/Scripts/jquery.validate.min.js" type="text/javascript"></script>
    <script type="text/javascript">
        $("#formCreate").validate({
            rules: {
                Name: {
                    required: true,
                },
                Title: {
                },
                Action: {
                },
                Controller: {
                },
                Url: {
                },
                Icon: {
                },
                SubMenuJson: {
                },
                SortOrder: {
                    number: true,
                },
            }
        });

        $(".kendo-dropdownlist").kendoDropDownList({
            filter: "contains"
        });

        $("button[name='createNext']").click(function (e) {
            var url = $("#formCreate").attr("action") + "?createNext=true";
            $("#formCreate").attr("action", url);
        });

        $(".kendo-datetimepicker").kendoDateTimePicker({
            format: "yyyy-MM-dd HH:mm"
        });
    </script>
}

App/Views/Menu/Details.cshtml
@model Domain.Infrastructure.Menu

@{
    ViewBag.Title = "Details";

    var webApiUrl = System.Configuration.ConfigurationManager.AppSettings["webApiUrl"];
}

<div class="panel">
    <div class="panel-header border-bottom">
        <h2>
            <span class="fa fa-info-circle"></span> <strong>Menu - Details</strong>
        </h2>
    </div>
    <div class="panel-content">
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Title)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Title)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Action)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Action)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Controller)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Controller)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Url)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Url)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Icon)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Icon)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.SortOrder)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.SortOrder)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.SubMenu)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.SubMenu)
            </dd>
        </dl>
        <div id="tabstrip">
            <ul>
                <li class="k-state-active">
                    RoleMenus
                </li>
                <li class="">
                    Logs
                </li>
            </ul>
            <div id="grid-RoleMenus"></div>
            <div id="grid-logs"></div>
        </div>
        <div style="height: 20px;"></div>
    </div>
    <div class="panel-footer">
        <p class="pull-right">
            @Html.ActionLink("Edit", "Edit", new { id = ViewBag.Id }) |
            @Html.ActionLink("Menu List", "Index")
            @if (Request.UrlReferrer != null)
            {
                @: | <a class="bottomNav" onclick="history.go(-1); return false;" href="#">Back</a><br />
            }
        </p>
        <div class="clearfix"></div>
    </div>
</div>

@section scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            $("#tabstrip").kendoTabStrip({
                animation: {
                    open: {
                        effects: "fadeIn"
                    }
                }
            });
        });
        var dsRoleMenus = new kendo.data.DataSource({
            type: "json",
            transport: {
                read: {
                    url: "@(webApiUrl)RoleMenus",
                    dataType: "json",
                    contentType: "application/json"
                },
                parameterMap: function (options, operation) {
                    if (operation === "destroy") {
                        return null;
                    } else if (operation !== "read" && options.models) {
                        return { models: kendo.stringify(options.models) };
                    } else {
                        return "q=" + JSON.stringify(options);
                    }
                }
            },
            schema: {
                data: "Data",
                total: "Total",
                model: {
                    id: 'Id'
                }
            },
            filter: {
                field: "MenuId",
                operator: "eq",
                value: "guid'@ViewBag.Id'"
            },
            serverFiltering: true,
            serverPaging: true,
            serverSorting: true,
            pageSize: 10
        });

        $("#grid-RoleMenus").kendoGrid({
            dataSource: dsRoleMenus,
            dataBound: gridDataBound,
            noDataMessage: 'Currently no RoleMenus available',
            sortable: true,
            filterable: {
                mode: "row"
            },
            pageable: {
                refresh: true,
                pageSizes: true,
                buttonCount: 5
            },
            groupable: true,
            columns: [
                {
                    field: "Role",
                    title: "Role",
                    template: function (data) {
                        return '<a href="@Url.Action("Details","ApplicationRole")/' + data.Role.Id + '">' + data.Role.Name + '</a>';
                    }
                },
                "SortOrder",
                {
                    command: [
                        {
                            name: 'Details',
                            click: function (data) {
                                var dataItem = this.dataItem($(data.currentTarget).closest("tr"));
                                window.location = "@Url.Action("Details", "RoleMenu")/" + dataItem.Id;
                            },
                            text: "<button class='btn btn-default btn-transparent btn-sm p-0' title='Details'><span class='fa fa-search'></span></button>"
                        }
                    ],
                    width: 100
                }
            ]
        });

        var dsLogs = new kendo.data.DataSource({
            type: "json",
            transport: {
                read: {
                    url: "@(webApiUrl)logs/Menus/@ViewBag.Id",
                    dataType: "json",
                    contentType: "application/json"
                },
                parameterMap: function (options, operation) {
                    if (operation === "destroy") {
                        return null;
                    } else if (operation !== "read" && options.models) {
                        return { models: kendo.stringify(options.models) };
                    } else {
                        return "q=" + JSON.stringify(options);
                    }
                }
            },
            schema: {
                data: "Data",
                total: "Total",
                model: {
                    id: 'Id',
                    fields: {
                        EventDateUTC: {
                            type: "date"
                        }
                    }
                }
            },
            serverFiltering: true,
            serverPaging: true,
            serverSorting: true,
            pageSize: 10
        });

        $("#grid-logs").kendoGrid({
            dataSource: dsLogs,
            sortable: true,
            filterable: {
                mode: "row"
            },
            pageable: {
                refresh: true,
                pageSizes: true,
                buttonCount: 5
            },
            groupable: true,
            columns: [
                {
                    field: "EventType",
                    title: "Type"
                },
                {
                    field: "EventDateUTC",
                    title: "Change Date",
                    format: "{0: yyyy-MM-dd HH:mm:ss}"
                },
                {
                    field: "ColumnName",
                    title: "Column"
                },
                {
                    field: "OriginalValue",
                    title: "Original"
                },
                {
                    field: "NewValue",
                    title: "New"
                },
                {
                    field: "UserName",
                    title: "By"
                }
            ]
        });
    </script>
}