App/Controllers/SolutionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.OleDb;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Domain.Models;
using App.DAL;
using App.Enums;
using Microsoft.AspNet.Identity;
using App.Infrastructure;
using System.Xml;
using System.Configuration;
using System.Data.SqlClient;

namespace App.Controllers
{
    public class SolutionEventArgs : EventArgs
    {
        public readonly Solution After;
        public readonly CrudEventEnumStatus Status;

        public SolutionEventArgs(Solution after, CrudEventEnumStatus status)
        {
            this.After = after;
            this.Status = status;
        }
    }

    public class SolutionController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public static event EventHandler<SolutionEventArgs> AfterCall;

        protected virtual void OnCrudOperation(SolutionEventArgs e)
        {
            if (AfterCall != null)
            {
                AfterCall(this, e);
            }
        }

        [PermissionAuthorization("support_read")]
        public ActionResult Index()
        {
            
             return View();        
        }
        
        public ActionResult IndexUser()
        {
            return View();
        }

        #region testIMPORT
        /// <summary>
        /// actionresult for import - using SQL syntax
        /// 
        /// </summary>
        /// <param name="file"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Index(HttpPostedFileBase file)
        {
            DataSet ds = new DataSet();
            if (Request.Files["file"].ContentLength > 0)
            {
                string FileExtension = System.IO.Path.GetExtension(Request.Files["file"].FileName);
                if (FileExtension == ".xls" || FileExtension == ".xlsx")
                {
                    string fileLocation = Server.MapPath("~/Content/") + Request.Files["file"].FileName;
                    //if there is a same file name in file location, delete it
                    if (System.IO.File.Exists(fileLocation))
                    {
                        System.IO.File.Delete(fileLocation);
                    }
                    Request.Files["file"].SaveAs(fileLocation);
                    
                    //init connection string
                    string excelConnectionString = string.Empty;
                    excelConnectionString = "Provider=Microsoft.ACE.OLEDB.12.0; Data Source=" + fileLocation + ";Extended Properties=\"Excel 12.0;HDR=Yes;IMEX=2\"";

                    //connection string for xls format
                    if (FileExtension == ".xls")
                    {
                        excelConnectionString = "Provider= Microsoft.Jet.OLEDB.4.0;Data Source=" + fileLocation + ";Extended Properties=\"Excel 8.0;HDR=yes;IMEX=2\"";
                    }
                    //connection string for xlsx format
                    if (FileExtension == ".xlsx")
                    {
                        excelConnectionString = "Provider=Microsoft.ACE.OLEDB.12.0; Data Source=" + fileLocation + ";Extended Properties=\"Excel 12.0;HDR=Yes;IMEX=2\"";
                    }


                    //create connection to workbook and OLEDB namespace
                    OleDbConnection excelConnection = new OleDbConnection(excelConnectionString);
                    excelConnection.Open();
                    DataTable dt = new DataTable();

                    dt = excelConnection.GetOleDbSchemaTable(OleDbSchemaGuid.Tables, null);
                    if (dt == null)
                    {
                        return null;
                    }

                    String[] excelsheets = new String[dt.Rows.Count];
                    int t = 0;

                    //excel data saved in temp files
                    foreach (DataRow row in dt.Rows)
                    {
                        excelsheets[t] = row["TABLE_NAME"].ToString();
                        t++;
                    }
                    OleDbConnection excelConnection1 = new OleDbConnection(excelConnectionString);

                    string query = string.Format("Select * from [{0}]", excelsheets[0]);
                    using (OleDbDataAdapter dataAdapter = new OleDbDataAdapter(query, excelConnection1))
                    {
                        dataAdapter.Fill(ds);
                    } 
                }
                if (FileExtension.ToString().ToLower().Equals(".xml")){
                    string fileLocation = Server.MapPath("~/Content/")+ Request.Files["FileUpload"].FileName;
                    if (System.IO.File.Exists(fileLocation)){
                        System.IO.File.Delete(fileLocation);
                    }
                    Request.Files["FileUpload"].SaveAs(fileLocation);
                    XmlTextReader xmlreader = new XmlTextReader(fileLocation);

                    ds.ReadXml(xmlreader);
                    xmlreader.Close();
                }
                //conection using SQL
                for (int i=0;i<ds.Tables[0].Rows.Count;i++)
                {
                    var _isDeleted = string.Empty;
                    _isDeleted = ds.Tables[0].Rows[i][7].ToString();
                    if (string.IsNullOrWhiteSpace(_isDeleted)) { _isDeleted = false.ToString(); }
                    string conn = ConfigurationManager.ConnectionStrings["ScaffoldTR"].ConnectionString;
                    SqlConnection con = new SqlConnection(conn);
                    string query = "SET IDENTITY_INSERT Solution ON " +
                        "BEGIN TRY INSERT into Solution(Id, Title, Content, CreatorId, CreatedAt, LastUpdateTime, IsPublished, IsDeleted) Values('" +
                        ds.Tables[0].Rows[i][0].ToString() + "','" +
                        ds.Tables[0].Rows[i][1].ToString() + "','" +
                        ds.Tables[0].Rows[i][2].ToString() + "','" +
                        ds.Tables[0].Rows[i][3].ToString() + "','" +
                        ds.Tables[0].Rows[i][4].ToString() + "','" +
                        ds.Tables[0].Rows[i][5].ToString() + "','" +
                        ds.Tables[0].Rows[i][6].ToString() + "','" +
                        _isDeleted + "') END TRY " +
                        "BEGIN CATCH " +
                        "IF ERROR_NUMBER() = 2627 " +
                        "UPDATE Solution SET " +
                        "Title ='" + ds.Tables[0].Rows[i][1].ToString() + "'," +
                        "Content ='" + ds.Tables[0].Rows[i][2].ToString() + "'," +
                        "CreatorId ='" + ds.Tables[0].Rows[i][3].ToString() + "'," +
                        "CreatedAt ='" + ds.Tables[0].Rows[i][4].ToString() + "'," +
                        "LastUpdateTime ='" + ds.Tables[0].Rows[i][5].ToString() + "'," +
                        "IsPublished ='" + ds.Tables[0].Rows[i][6].ToString() + "', " +
                        "IsDeleted ='" + ds.Tables[0].Rows[i][7].ToString() + "' " +
                        "Where Id='" + ds.Tables[0].Rows[i][0].ToString() + "' END CATCH " +
                        "SET IDENTITY_INSERT Solution OFF ";
                    con.Open();
                    SqlCommand cmd = new SqlCommand(query, con);
                    cmd.ExecuteNonQuery();
                    con.Close();
                }
            }
            return View();
        }
        #endregion

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Solution solution = db.Solutions.Find(id);
            ViewBag.Id = id;
            if (solution == null)
            {
                return HttpNotFound();
            }
            return View(solution);
        }

        [PermissionAuthorization("support_crud")]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [PermissionAuthorization("support_crud")]
        public ActionResult Create(Solution solution)
        {
            if (ModelState.IsValid)
            {
                solution.CreatorId = User.Identity.GetUserId();
                db.Solutions.Add(solution);

                db.SaveChanges(User.Identity.GetUserName());

                OnCrudOperation(new SolutionEventArgs(solution, CrudEventEnumStatus.Create));

                if (!string.IsNullOrWhiteSpace(Request.QueryString["createNext"]))
                {
                    if (Request.QueryString["createNext"] == "true")
                    {
                        TempData["Created"] = true;
                        TempData["Alert"] = "Berhasil menambahkan Solution";
                        TempData["AlertClass"] = "success";

                        return RedirectToAction("Create");
                    }
                }

                return RedirectToAction("Details", new { id = solution.Id});
            }

            TempData["Alert"] = "Gagal menambahkan Solution. Harap periksa kembali data yang anda input.";
            TempData["AlertClass"] = "danger";

            return View(solution);
        }

        [PermissionAuthorization("support_crud")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Solution solution = db.Solutions.Find(id);
            ViewBag.Id = id;

            if (solution == null)
            {
                return HttpNotFound();
            }

            return View(solution);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [PermissionAuthorization("support_crud")]
        public ActionResult Edit(Solution solution)
        {

App/Controllers/WebApi/SolutionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Linq.Dynamic;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Http.Description;
using AutoMapper;
using AutoMapper.QueryableExtensions;
using Kendo.DynamicLinq;
using Newtonsoft.Json;
using Domain.Models;
using App.DAL;
using App.Enums;
using App.Helper;
using Domain.Models.ViewModels;
using Microsoft.AspNet.Identity;

namespace App.Controllers.WebApi
{
    public class SolutionsControllerEventArgs : EventArgs
    {
        public readonly Solution After;
        public readonly CrudEventEnumStatus Status;

        public SolutionsControllerEventArgs(Solution after, CrudEventEnumStatus status)
        {
            this.After = after;
            this.Status = status;
        }
    }

    public class SolutionsController : ApiController
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public static event EventHandler<SolutionsControllerEventArgs> AfterCall;

        protected virtual void OnCrudOperation(SolutionsControllerEventArgs e)
        {
            if (AfterCall != null)
            {
                AfterCall(this, e);
            }
        }

        // GET: api/Solutions
        public DataSourceResult GetSolutions(HttpRequestMessage requestMessage)
        {
            DataSourceRequest request =
                JsonConvert.DeserializeObject<DataSourceRequest>(requestMessage.RequestUri.ParseQueryString().GetValues("q")[0]);

            if (request.Filter != null && !request.Filter.Filters.Any())
            {
                request.Filter = null;
            }
            else
            {
                request.Filter.ToCustomExpression();
            }
            var _currUserId = User.Identity.GetUserId();
            var result = db.Solutions.Include(x => x.Creator).Include(x => x.Tickets).AsQueryable();
            //if (User.IsInRole("User"))
            //{
            //    //result = db.Solutions.Where((x => x.Tickets.Where(y => y.CreatorId) == _currUserId)).Include(x => x.Creator).Include(x => x.Tickets).AsQueryable();
            //    //result = db.Solutions.Include(x => x.Creator).Include(x => x.Tickets.Where(y=>y.CreatorId == _currUserId)).AsQueryable();
            //}

            return result
                .OrderBy(x => x.Id)
                .Project()
                .To<SolutionViewModel>()
                .ToDataSourceResult(request.Take, request.Skip, request.Sort, request.Filter);
        }

        // GET: api/Solutions/5
        [ResponseType(typeof(SolutionViewModel))]
        public IHttpActionResult GetSolution(int id)
        {
            Solution solution = db.Solutions.Find(id);
            if (solution == null)
            {
                return NotFound();
            }

            return Ok(Mapper.Map<Solution, SolutionViewModel>(solution));
        }

        // PUT: api/Solutions/5
        [ResponseType(typeof(void))]
        public IHttpActionResult PutSolution(int id, SolutionViewModel solution)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (id != solution.Id)
            {
                return BadRequest();
            }

            var tempsolution = solution.ToEntity();

            db.Entry(tempsolution).State = EntityState.Modified;

            try
            {
                db.SaveChanges(User.Identity.GetUserName());
                OnCrudOperation(new SolutionsControllerEventArgs(tempsolution, CrudEventEnumStatus.Update));
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!SolutionExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return StatusCode(HttpStatusCode.NoContent);
        }

        // POST: api/Solutions
        [ResponseType(typeof(SolutionViewModel))]
        public IHttpActionResult PostSolution(SolutionViewModel solution)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            var tempsolution = solution.ToEntity();

            db.Solutions.Add(tempsolution);
            db.SaveChanges(User.Identity.GetUserName());
            OnCrudOperation(new SolutionsControllerEventArgs(tempsolution, CrudEventEnumStatus.Create));

            return CreatedAtRoute("DefaultApi", new { id = solution.Id }, 
                    Mapper.Map<Solution, SolutionViewModel>(tempsolution));
        }

        // DELETE: api/Solutions/5
        [ResponseType(typeof(SolutionViewModel))]
        public IHttpActionResult DeleteSolution(int id)
        {
            Solution solution = db.Solutions.Find(id);
            if (solution == null && !User.IsInRole("Admin"))
            {
                return NotFound();
            }

            db.Solutions.Remove(solution);
            db.SaveChanges(User.Identity.GetUserName());
            OnCrudOperation(new SolutionsControllerEventArgs(solution, CrudEventEnumStatus.Delete));

            return Ok(Mapper.Map<Solution, SolutionViewModel>(solution));
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private bool SolutionExists(int id)
        {
            return db.Solutions.Count(e => e.Id == id) > 0;
        }
    }
}

App/Views/Solution/Create.cshtml
@model Domain.Models.Solution

@{
    ViewBag.Title = "Create";
    var webApiUrl = System.Configuration.ConfigurationManager.AppSettings["webApiUrl"];
}

<div class="panel">
    <div class="panel-header border-bottom">
        <h2>
            <span class="fa fa-plus-circle"></span> <strong>Solution - Create</strong>
        </h2>
    </div>
    <div class="panel-content">
    @using (Html.BeginForm("Create", "Solution", FormMethod.Post, new { @id = "formCreate" })) 
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                    @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Title, new { @class = "form-control form-white" })
                            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                        </div>
            </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Content, new { @class = "form-control form-white" })
                            @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
                        </div>
            </div>

                @*<div class="form-group">
                    @Html.LabelFor(model => model.CreatorId, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                            @Html.DropDownList("CreatorId", new SelectList(new List<string>()), htmlAttributes: new { @class = "form-control kendo-dropdownlist", @id = "CreatorId" })
                                @Html.ValidationMessageFor(model => model.CreatorId, "", new { @class = "text-danger" })
                        </div>
            </div>*@

                @*<div class="form-group">
                    @Html.LabelFor(model => model.CreatedAt, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.CreatedAt, new { @class = "form-control form-white" })
                            @Html.ValidationMessageFor(model => model.CreatedAt, "", new { @class = "text-danger" })
                        </div>
            </div>*@

                @*<div class="form-group">
                    @Html.LabelFor(model => model.LastUpdateTime, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.LastUpdateTime, new { @class = "form-control form-white" })
                            @Html.ValidationMessageFor(model => model.LastUpdateTime, "", new { @class = "text-danger" })
                        </div>
            </div>*@

                <div class="form-group">
                    @Html.LabelFor(model => model.IsPublished, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="checkbox">
                        @Html.EditorFor(model => model.IsPublished)
                                @Html.ValidationMessageFor(model => model.IsPublished, "", new { @class = "text-danger" })
                                </div>
                    </div>
            </div>

                <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="k-button" /> &nbsp; <button type="submit" value="true" name="createNext" class="k-button k-primary">Save and create next</button>
                </div>
            </div>
        </div>
    }
    </div>
    <div class="panel-footer">
        <p class="pull-right">
            @Html.ActionLink("Solution List", "Index")
            @if (Request.UrlReferrer != null)
            {
                @: | <a class="bottomNav" onclick="history.go(-1); return false;" href="#">Back</a><br/>
            }
        </p>
        <div class="clearfix"></div>
    </div>
</div>

@section scripts{
    <script src="~/Scripts/jquery.validate.min.js" type="text/javascript"></script>
    <script type="text/javascript">
        $("#formCreate").validate({
            rules: {
                Title: {
                    required: true,
                },
                Content: {
                    required: true,
                },
                CreatorId: {
                },
                CreatedAt: {
                },
                LastUpdateTime: {
                },
                IsPublished: {
                },
            }
        });

        $(".kendo-dropdownlist").kendoDropDownList({
            filter: "contains"
        });

        $("button[name='createNext']").click(function (e) {
            var url = $("#formCreate").attr("action") + "?createNext=true";
            $("#formCreate").attr("action", url);
        });

        var dsCreatorId = new kendo.data.DataSource({
            type: "json",
            transport: {
                read: {
                    url: "@(webApiUrl)Creators",
                    dataType: "json",
                    contentType: "application/json",
                },
                parameterMap: function (options, operation) {
                    if (operation === "destroy") {
                        return null;
                    } else if (operation !== "read" && options.models) {
                        return { models: kendo.stringify(options.models) };
                    } else {
                        return "q=" + JSON.stringify(options);
                    }
                }
            },
            schema: {
                data: "Data",
                total: "Total",
                model: {
                    id: 'Id',
                    fields: {
                        
                    }
                }
            },
            serverFiltering: true,
            serverPaging: true,
            pageSize: 7
        });

        $("#CreatorId").kendoDropDownList({
            filter: "contains",
            dataSource: dsCreatorId,
            dataTextField: "Email",
            dataValueField: "Id",
        });

        $(".kendo-datetimepicker").kendoDateTimePicker({
            format: "yyyy-MM-dd HH:mm"
        });
    </script>
}

App/Views/Solution/Edit.cshtml
@model Domain.Models.Solution

@{
    ViewBag.Title = "Edit";

    var webApiUrl = System.Configuration.ConfigurationManager.AppSettings["webApiUrl"];
}
<div class="panel">
    <div class="panel-header border-bottom">
        <h2>
            <span class="fa fa-edit"></span> <strong>Solution - Edit</strong>
        </h2>
    </div>
    <div class="panel-content">
        @using (Html.BeginForm("Edit", "Solution", FormMethod.Post, new { @id = "formEdit" }))
        {
            @Html.AntiForgeryToken()
    
            <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                @Html.HiddenFor(model => model.Id)

                        <div class="form-group">
                            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Title, new { @class = "form-control form-white" })
                                        @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                                    </div>
                </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Content, new { @class = "form-control form-white" })
                                        @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
                                    </div>
                </div>
                @Html.HiddenFor(m => m.CreatorId)
                @Html.HiddenFor(m => m.CreatedAt)
                @Html.HiddenFor(m => m.LastUpdateTime)
                        @*<div class="form-group">
                            @Html.LabelFor(model => model.CreatorId, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                        @Html.DropDownList("CreatorId", new SelectList(new List<string>()), htmlAttributes: new { @class = "form-control kendo-dropdownlist" })
                                                @Html.ValidationMessageFor(model => model.CreatorId, "", new { @class = "text-danger" })
                                    </div>
                </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.CreatedAt, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.CreatedAt, new { @class = "form-control form-white" })
                                        @Html.ValidationMessageFor(model => model.CreatedAt, "", new { @class = "text-danger" })
                                    </div>
                </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.LastUpdateTime, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.LastUpdateTime, new { @class = "form-control form-white" })
                                        @Html.ValidationMessageFor(model => model.LastUpdateTime, "", new { @class = "text-danger" })
                                    </div>
                </div>*@

                        <div class="form-group">
                            @Html.LabelFor(model => model.IsPublished, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                <div class="checkbox">
                                @Html.EditorFor(model => model.IsPublished)
                                            @Html.ValidationMessageFor(model => model.IsPublished, "", new { @class = "text-danger" })
                                            </div>
                            </div>
                </div>

                        <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="k-button k-primary" />
                    </div>
                </div>
            </div>
        }
    </div>
    <div class="panel-footer">
        <p class="pull-right">
            @Html.ActionLink("Details", "Details", new { id = ViewBag.Id }) |
            @Html.ActionLink("Solution List", "Index")
            @if (Request.UrlReferrer != null)
            {
                @: | <a class="bottomNav" onclick="history.go(-1); return false;" href="#">Back</a><br/>
            }
        </p>
        <div class="clearfix"></div>
    </div>
</div>

@section scripts{
    <script src="~/Scripts/jquery.validate.min.js" type="text/javascript"></script>
    <script type="text/javascript">
        $("#formEdit").validate({
            rules: {
                Title: {
                    required: true,
                },
                Content: {
                    required: true,
                },
                CreatorId: {
                },
                CreatedAt: {
                },
                LastUpdateTime: {
                },
                IsPublished: {
                },
            }
        });
        var dsCreatorId = new kendo.data.DataSource({
            type: "json",
            transport: {
                read: {
                    url: "@(webApiUrl)Creators",
                    dataType: "json",
                    contentType: "application/json",
                },
                parameterMap: function (options, operation) {
                    if (operation === "destroy") {
                        return null;
                    } else if (operation !== "read" && options.models) {
                        return { models: kendo.stringify(options.models) };
                    } else {
                        return "q=" + JSON.stringify(options);
                    }
                }
            },
            schema: {
                data: "Data",
                total: "Total",
                model: {
                    id: 'Id',
                    fields: {
                        
                    }
                }
            }
        });

        

        $(".kendo-datetimepicker").kendoDateTimePicker({
            format: "yyyy-MM-dd HH:mm"
        });
    </script>
}